# Generated by Django 4.0.6 on 2022-07-11 20:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='message_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default='{fv}', size=100),
            preserve_default=False,
        ),
    ]
