# Generated by Django 4.0.6 on 2022-07-26 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_telegramuser_bot_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.telegramuser')),
            ],
        ),
    ]
