# Generated by Django 4.0.6 on 2022-11-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_telegramsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramsettings',
            name='auto_send',
            field=models.BooleanField(default=False),
        ),
    ]
