# Generated by Django 4.1.3 on 2022-11-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_alter_telegramsettings_auto_send"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramsettings",
            name="auto_send_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
