# Generated by Django 4.1.3 on 2022-11-23 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0014_telegramsettings_auto_send_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="telegramsettings",
            old_name="auto_send_message",
            new_name="auto_send_text",
        ),
    ]
