# Generated by Django 4.1.3 on 2022-12-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_rename_auto_send_message_telegramsettings_auto_send_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramsettings",
            name="bot_status",
            field=models.BooleanField(default=False),
        ),
    ]
