# Generated by Django 4.0.6 on 2022-07-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the bot', max_length=100)),
                ('token', models.CharField(help_text='Token of the bot', max_length=100)),
                ('chat_id', models.IntegerField(help_text='Chat id of the bot')),
            ],
            options={
                'verbose_name': 'Bot',
                'verbose_name_plural': 'Bots',
            },
        ),
    ]
