# Generated by Django 4.0.6 on 2022-07-09 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the cryptocurrency. eg: Bitcoin, Ethereum, Litecoin, etc.', max_length=100)),
                ('symbol', models.CharField(help_text='Symbol of the cryptocurrency. eg: BTC, ETH, LTC, etc.', max_length=100)),
            ],
            options={
                'verbose_name': 'Crypto Currency',
                'verbose_name_plural': 'Crypto Currencies',
            },
        ),
        migrations.CreateModel(
            name='Wallets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the wallet. eg: Bitcoin Wallet, Ethereum Wallet, Litecoin Wallet, etc.', max_length=100)),
                ('address', models.CharField(help_text='Address of the wallet. eg: 123123123123123123123123123123123123123', max_length=100)),
                ('cryptocurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cryptocurrency', to='crypto.cryptocurrency')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
    ]
