# Generated by Django 4.0.6 on 2022-07-09 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Crypto Network',
                'verbose_name_plural': 'Crypto Networks',
            },
        ),
        migrations.AddField(
            model_name='wallets',
            name='network',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='network', to='crypto.cryptonetwork'),
            preserve_default=False,
        ),
    ]
