# Generated by Django 4.0.6 on 2022-07-09 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_cryptonetwork_wallets_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallets',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network', to='crypto.cryptonetwork'),
        ),
    ]
